In [20]:
import pandas as pd

file_path = "/data_8TB_2/xiangling_workspace/NEMSIS_ASCII_25/ESITUATION_09REF.txt"

df_ESITUATION_09REF = pd.read_csv(file_path, sep=None, engine="python", nrows=5)
df_ESITUATION_09REF

  'eSituation_09'  |                               'DiagnosisCodeDescr'
0      A02.9       |  Salmonella infection, unspecified             ...
1      A04.72      |  Enterocolitis due to Clostridium difficile, no...
2      A04.9       |  Bacterial intestinal infection, unspecified   ...
3      A05.1       |  Botulism food poisoning                       ...
4      A05.9       |  Bacterial foodborne intoxication, unspecified ...

In [21]:
import pandas as pd

file_path = "/data_8TB_2/xiangling_workspace/NEMSIS_ASCII_25/FACTPCRADDITIONALSYMPTOM.txt"

df_ESITUATION_09REF = pd.read_csv(file_path, sep=None, engine="python", nrows=5)
df_ESITUATION_09REF

    'PcrKey'  | 'eSituation_10' |.1 'eSituation_10PN'
0  159958910  |      R53.81       |
1  159958910  |      R53.83       |
2  159958910  |      R63.1        |
3  159958910  |      R68.2        |
4  194290514  |      R20.0        |

In [22]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2si_protocol.txt"

df_nemsis_pcr2si_protocol = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2si_protocol.head(10)

,PcrKey,PrimarySymptomCode,PrimaryImpressionCode,AdditionalSymptomCode,SecondaryImpressionCode,ProtocolIds
0,348923172,R10.9,R10.9,R11.0,R11.0,23
1,348911620,R10.9,R10.84,R11.2 R10.2,R10.2,23
2,348900041,R10.9,R10.9,M54.9 R31.9,R31.9 M54.9,23
3,348920792,R10.9,R10.9,I46.9,I46.9,2 23
4,348930298,R10.9,R10.84,M54.5 R10.0,M54.5,23
5,348917992,R10.9,R10.9,R19.7,R19.7,23
6,348919124,R10.9,R10.9,R11.10,R11.10,23 29
7,348892873,R10.9,R10.9,Z04.9,Z04.9,23
8,348889266,R10.9,R10.9,R11.10,R11.10,23
9,348885766,R10.9,R10.9,R53.1,R53.1,23

In [1]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2si_protocol_single_label.txt"

df_nemsis_pcr2si_protocol_single_label = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2si_protocol_single_label.head(10)

,PcrKey,PrimarySymptomCode,PrimaryImpressionCode,AdditionalSymptomCode,SecondaryImpressionCode,ProtocolIds
0,348923172,R10.9,R10.9,R11.0,R11.0,23
1,348911620,R10.9,R10.84,R11.2 R10.2,R10.2,23
2,348900041,R10.9,R10.9,M54.9 R31.9,R31.9 M54.9,23
3,348930298,R10.9,R10.84,M54.5 R10.0,M54.5,23
4,348917992,R10.9,R10.9,R19.7,R19.7,23
5,348892873,R10.9,R10.9,Z04.9,Z04.9,23
6,348889266,R10.9,R10.9,R11.10,R11.10,23
7,348885766,R10.9,R10.9,R53.1,R53.1,23
8,348978764,R10.9,R10.9,R11.10 M54.9,R11.10 M54.9,23
9,348619552,R10.9,R10.9,R11.0 R19.7 R11.10 J11.1,J11.1 R11.10 R11.0 R19.7,23

In [2]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2si_protocol_multi_label.txt"

df_nemsis_pcr2si_protocol_multi_label = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2si_protocol_multi_label.head(10)

,PcrKey,PrimarySymptomCode,PrimaryImpressionCode,AdditionalSymptomCode,SecondaryImpressionCode,ProtocolIds
0,348920792,R10.9,R10.9,I46.9,I46.9,2 23
1,348919124,R10.9,R10.9,R11.10,R11.10,23 29
2,349077159,R10.9,R10.9,I49.9,I49.9,23 37
3,349764494,R10.9,R10.9,Z03.89,Z03.89,23 25
4,350228709,R10.9,R10.84,R07.89,R07.9,23 27
5,350178697,R10.9,R10.0,I95.9 I48.91,K59.1 R11.2,31 33
6,350421528,R10.9,R10.9,R07.9,R07.9,23 27
7,350456951,R10.9,R10.9,R53.81 R11.0 R06.00 R07.9,R07.9 R11.0 R53.81 R06.00,27 34
8,350422704,R10.9,R10.9,J11.1,J11.1,12 23
9,350458876,R10.9,R10.9,R07.9,R07.9,23 27

In [23]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2protocol.txt"

df_nemsis_pcr2protocol = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2protocol.head(10)

      PcrKey  ProtocolId
0  402740315          37
1  388248684          37
2  380662081          37
3  360764196          37
4  356371616          37
5  397825742          37
6  407622324          37
7  371239087          37
8  353994756          37
9  377134744          37

In [24]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2si.txt"

df_nemsis_pcr2si = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2si.head(10)

,PcrKey,PrimarySymptomCode,PrimaryImpressionCode,AdditionalSymptomCode,SecondaryImpressionCode
0,348926643,R10.9,M54.9,R11.0,R11.0
1,348914180,R10.9,R10.84,R11.2,R11
2,348923172,R10.9,R10.9,R11.0,R11.0
3,348895021,R10.9,N20.0,R11.2,R11.1
4,348905840,R10.9,R10.9,R51 T14.90XA,T14.90XA
5,348900811,R10.9,R10.9,R11.0 R11.10 E86.0,E86.0 R11.10 R11.0
6,348911620,R10.9,R10.84,R11.2 R10.2,R10.2
7,348893716,R10.9,R52,G40.3,G40.909
8,348900041,R10.9,R10.9,M54.9 R31.9,R31.9 M54.9
9,348916008,R10.9,F10.92,R11.2 G47.00 F41.9 R10.2 R33.9,F99

In [2]:
import pandas as pd

file_path = "/home/xiangling/nemsis_cache_files/nemsis_pcr2si_protocol_single_label_symptom_text.txt"

df_nemsis_pcr2si_protocol_single_label_symptom_text = pd.read_csv(file_path, sep="~\\|~", engine="python")
df_nemsis_pcr2si_protocol_single_label_symptom_text.head(10)

,PcrKey,PrimarySymptomDescription,PrimaryImpressionDescription,AdditionalSymptomDescription,SecondaryImpressionDescription,ProtocolIds
0,348923172,unspecified abdominal pain,unspecified abdominal pain,nausea,nausea,23
1,348911620,unspecified abdominal pain,generalized abdominal pain,"nausea with vomiting, unspecified ; pelvic and...",pelvic and perineal pain,23
2,348900041,unspecified abdominal pain,unspecified abdominal pain,"dorsalgia, unspecified ; hematuria, unspecified","hematuria, unspecified ; dorsalgia, unspecified",23
3,348930298,unspecified abdominal pain,generalized abdominal pain,low back pain ; acute abdomen,low back pain,23
4,348917992,unspecified abdominal pain,unspecified abdominal pain,"diarrhea, unspecified","diarrhea, unspecified",23
5,348892873,unspecified abdominal pain,unspecified abdominal pain,encounter for examination and observation for ...,encounter for examination and observation for ...,23
6,348889266,unspecified abdominal pain,unspecified abdominal pain,"vomiting, unspecified","vomiting, unspecified",23
7,348885766,unspecified abdominal pain,unspecified abdominal pain,weakness,weakness,23
8,348978764,unspecified abdominal pain,unspecified abdominal pain,"vomiting, unspecified ; dorsalgia, unspecified","vomiting, unspecified ; dorsalgia, unspecified",23
9,348619552,unspecified abdominal pain,unspecified abdominal pain,"nausea ; diarrhea, unspecified ; vomiting, uns...",influenza due to unidentified influenza virus ...,23